"use client";

// import localFont from "next/font/local";
import "./globals.scss";
import { NextUIProvider } from "@nextui-org/react";
import { Analytics } from "@vercel/analytics/react";
import Header from "../components/Header";
import Footer from "../components/footer";

import { I18nextProvider } from "react-i18next";
import i18n from "../i18n"; // Импортируем экземпляр i18n

import { motion, AnimatePresence } from "framer-motion";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // используем для отслеживания маршрутов
  return (
    <html lang="uk">
      <body>
        <NextUIProvider>
          <Header />
          <main
          // className="dark text-foreground bg-background"
          >
            <AnimatePresence>
              <motion.div
                key={pathname}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, x: 0 }}
                exist={{ opacity: 0, y: 15 }}
                transition={{ duration: 1 }}
              >
                <I18nextProvider i18n={i18n}>{children}</I18nextProvider>
              </motion.div>
            </AnimatePresence>
            <Analytics />
          </main>
          {/* <Footer /> */}
        </NextUIProvider>
      </body>
    </html>
  );
}
