"use client";

import localFont from "next/font/local";
import "./globals.scss";
import { NextUIProvider } from "@nextui-org/react";
import { Analytics } from "@vercel/analytics/react";
import Header from "../components/Header";
import Footer from "../components/footer";

import { motion, AnimatePresence } from "framer-motion";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // используем для отслеживания маршрутов
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Header />
          <main
          // className="dark text-foreground bg-background"
          >
            <AnimatePresence>
              <motion.div
                key={pathname}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, x: 0 }}
                exist={{ opacity: 0, y: 15 }}
                transition={{ duration: 1 }}
              >
                {children}
              </motion.div>
            </AnimatePresence>
            <Analytics />
          </main>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
